apriltag_node:
  ros__parameters:
    # setup (defaults)
    image_transport: "raw"  # REVERTED: Must be "raw" to prevent SIGABRT
    family: 36h11         
    size: 0.16          
    profile: false

    # tuning of detection
    max_hamming: 2
    detector:
      threads: 4
      decimate: 1.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false

    pose_estimation_method: "pnp"

    publish_tf: true
    approximate_sync: true